name: Build geoip.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3,6"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
      - "**/dependabot.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "CURRENT_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
        shell: bash

      - name: Get GeoLite2
        env:
          LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE }}
        run: |
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${LICENSE_KEY}&suffix=zip" -o GeoLite2-Country-CSV.zip
          unzip GeoLite2-Country-CSV.zip
          rm -f GeoLite2-Country-CSV.zip
          mv GeoLite2* geolite2

      - name: Build geoip.dat
        run: |
          go run ./

      - name: Generate sha256 checksum for dat files
        run: |
          cd ./output || exit 1
          for name in $(ls *.dat); do
            sha256sum ${name} > ./${name}.sha256sum
          done

      - name: Release and upload assets
        run: |
          gh release create ${{ env.TAG_NAME }} \
            -n "This release was created automatically at ${{ env.CURRENT_TIME }} (GMT+0)." \
            -t "${{ env.CURRENT_TIME }}" \
            ./output/geoip.dat \
            ./output/geoip.dat.sha256sum \
            ./output/geoip-only-cn-private.dat \
            ./output/geoip-only-cn-private.dat.sha256sum \
            ./output/cn.dat \
            ./output/cn.dat.sha256sum \
            ./output/private.dat \
            ./output/private.dat.sha256sum
        env:
          GH_TOKEN: ${{ github.token }}
